import type { Metadata } from "next";
import NunitoFont from 'next/font/local';
import Header from "./ui/header";
import { Providers } from "./providers";
import "./globals.css";

const nunito = NunitoFont({
  src: [
    {
      path: '../public/fonts/NunitoSans-ExtraBold.woff2',
      weight: '800',
      style: 'normal'
    },
    {
      path: '../public/fonts/NunitoSans-SemiBold.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../public/fonts/NunitoSans-Light.woff2',
      weight: '300',
      style: 'normal'
    }
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.className} antialiased`} suppressHydrationWarning >
      <body className="min-h-screen bg-grey-50 dark:bg-blue-950">
        <Providers attribute="data-theme" defaultTheme="system" enableSystem>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
